[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "AgentEconomist"
version = "0.1.0"
description = "Economic Simulation Agent"
requires-python = ">=3.11"

[tool.setuptools.packages.find]
where = [".."]
include = ["AgentEconomist*"]
